### PR TITLE
Enable dynamic link on Windows

### PR DESCRIPTION
**Pull request by nkshigeru**
bincrafters/community#1207

### CODE REVIEW

**Comment by ericLemanissier** [comment]
Thanks for the PR, but this should not be needed with https://github.com/bincrafters/conan-portaudio/commit/061e8c050d9418f4cb1b39c594a0c1ef89306d1f right ?

**Comment by nkshigeru** [comment]
@ericLemanissier Right.
Thank you for your work!

**Comment by nkshigeru** [comment]
@ericLemanissier Could you merge https://github.com/bincrafters/conan-portaudio/commit/061e8c050d9418f4cb1b39c594a0c1ef89306d1f into stable?

**Comment by ericLemanissier** [comment]
done in https://github.com/bincrafters/conan-portaudio/commit/d4ac4ad9502f9b7015d5fee679a5f8d540876026

**Pull request closed without merging**
